function tableout = importarPartidos(workbookFile,sheetName,startRow,endRow)
%IMPORTARPARTIDOS Import data from a spreadsheet
%   DATA = IMPORTARPARTIDOS(FILE) reads data from the first worksheet in the Microsoft Excel spreadsheet file named
%   FILE and returns the data as a table.
%
%   DATA = IMPORTARPARTIDOS(FILE,SHEET) reads from the specified worksheet.
%
%   DATA = IMPORTARPARTIDOS(FILE,SHEET,STARTROW,ENDROW) reads from the specified worksheet for the specified row
%   interval(s). Specify STARTROW and ENDROW as a pair of scalars or vectors of matching size for
%   dis-contiguous row intervals. To read to the end of the file specify an ENDROW of inf.%
% Example:
%   Partidos = importarPartidos('Partidos.xlsx','Primera',1,400);
%
%   See also XLSREAD.

% Auto-generated by MATLAB on 2017/09/04 11:02:57

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 3
    startRow = 1;
    endRow = 400;
end

%% Import the data, extracting spreadsheet dates in Excel serial date format
[~, ~, raw, dates] = xlsread(workbookFile, sheetName, sprintf('A%d:E%d',startRow(1),endRow(1)),'' , @convertSpreadsheetExcelDates);
for block=2:length(startRow)
    [~, ~, tmpRawBlock,tmpDateNumBlock] = xlsread(workbookFile, sheetName, sprintf('A%d:E%d',startRow(block),endRow(block)),'' , @convertSpreadsheetExcelDates);
    raw = [raw;tmpRawBlock]; %#ok<AGROW>
    dates = [dates;tmpDateNumBlock]; %#ok<AGROW>
end
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};
cellVectors = raw(:,[2,3]);
raw = raw(:,[4,5]);
dates = dates(:,1);

%% Create output variable
I = cellfun(@(x) ischar(x), raw);
raw(I) = {NaN};
data = reshape([raw{:}],size(raw));

%% Create table
tableout = table;

%% Allocate imported array to column variable names
dates(~cellfun(@(x) isnumeric(x) || islogical(x), dates)) = {NaN};
tableout.Fecha = datetime([dates{:,1}].', 'ConvertFrom', 'Excel', 'Format', 'MM/dd/yyyy');
tableout.Local = cellVectors(:,1);
tableout.Visitante = cellVectors(:,2);
tableout.GolesLocal = data(:,1);
tableout.GolesVisitante = data(:,2);

% For code requiring serial dates (datenum) instead of datetime, uncomment the following line(s) below to
% return the imported dates as datenum(s).

% tableout.Fecha=datenum(tableout.Fecha);

